parameters:
#    nca_jazz.example.class: Nca\JazzBundle\Example

services:
#    nca_jazz.example:
#        class: %nca_jazz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
